[[main]]
  name = "Connector"
  url = "/connector/get-started/overview"
  weight = 100

[[main]]
  name = "Application"
  url = "/application/get-started/overview"
  weight = 200

[[main]]
  name = "Reference"
  url = "/references/basics/overview"
  weight = 300

[[connector]]
  name = "Get started"
  weight = 101
  identifier = "connector-get-started"
  url = "/connector/get-started/overview"

[[connector]]
  name = "Setup"
  weight = 102
  identifier = "connector-setup"
  url = "/connector/setup"

[[references]]
  name = "Basics"
  weight = 301
  identifier = "references-basics"
  url = "/references/basics/overview"

[[references]]
  name = "Deal filter"
  weight = 302
  identifier = "references-deal-filter"
  url = "/references/deal-filter/overview"

[[application]]
  name = "Get started"
  weight = 201
  identifier = "application-get-started"
  url = "/application/get-started/overview"

[[application]]
  name = "Clients"
  weight = 202
  identifier = "application-clients"
  url = "/application/clients"

[[application]]
  name = "Pricing models"
  weight = 203
  identifier = "application-pricing-models"
  url = "/application/pricing-models"

[[application]]
  name = "Storage acceptance logic"
  weight = 204
  identifier = "storage-acceptance-logic"
  url = "/application/storage-acceptance-logic/"

[[application]]
  name = "Analytics"
  weight = 206
  identifier = "application-analytics"
  url = "/application/analytics/overview"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/CIDgravity/CIDgravity-X"
  post = "v0.1.0"
  weight = 10